### ISSUE TITLE
Document everything

### ISSUE THREAD

**Issue by Techcable** [DuckLogic/rust-idmap#1]
Writing documentation is unpleasant work, so I should probably add a `deny(missing_docs)` to force me to do it!

**Comment by mattdm** [comment]
On a related note: this uses feature attributes, so it requires a nightly rustc. It should probably say so in the readme and on crates.io?

(Or is there a way to make it work on stable that I am missing?)

**Comment by Techcable** [comment]
It's now stable by default. Nightly support will improve performance very slightly and can be enabled with feature="nightly" :smile:
